[build]
  functions = "netlify/functions" # Path to your functions directory
  publish = "."               # Publish directory (can be root for this app)
  command = "pip install -r requirements.txt && playwright install" # Install dependencies during build

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/deep2/:splat" # Route /api/* to your function
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/deep2" # Route all other requests (for index.html)
  status = 200